language: python
python:
  - "3.4"
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
  - "pypy"
services:
  - postgressql
env:
  - DJANGO="Django>=1.4,<1.5" DB="sqlite"
  - DJANGO="Django>=1.4,<1.5" DB="postgres"
  - DJANGO="Django>=1.5,<1.6" DB="sqlite"
  - DJANGO="Django>=1.5,<1.6" DB="postgres"
  - DJANGO="Django>=1.6,<1.7" DB="sqlite"
  - DJANGO="Django>=1.6,<1.7" DB="postgres"
  - DJANGO="Django>=1.7,<1.8" DB="sqlite"
  - DJANGO="Django>=1.7,<1.8" DB="postgres"
matrix:
  exclude:
    - python: "3.4"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.3"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "3.2"
      env: DJANGO="Django>=1.4,<1.5"
    - python: "2.6"
      env: DJANGO="Django>=1.7,<1.8"

before_script:
  - psql -c 'create database mydatabase;' -U postgres
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - if [ "$DB" == "postgres" ]; then pip install psycopg2; fi
  - pip install -q Django==$DJANGO --use-mirrors
# command to run tests, e.g. python setup.py test
script:
  - ./runtests.py --settings=tests.test_$DB
#script: cd tests/ && ./runtests.sh
